### ISSUE TITLE
Updated Docker Registry Location

### ISSUE THREAD

**Issue by smahony36** [geoffgbsn/unraid-templates#1]
Hi Geoff, 

Sorry is this is the wrong place to post this (it's my first time)

Looks like the docker registry location for HomeBridge has been updated. Can you please update the Unraid community apps xml to reflect? 

https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js/#:~:text=Users%20running%20in,homebridge/homebridge.

**Comment by benfishbus** [comment]
Echoing the above. If oznu/homebridge even still works, its Node.js is too far out of date to update to the latest Homebridge.

**Comment by geoffgbsn** [comment]
Update has been submitted
